### ISSUE TITLE
2 factor authenticatin does not seem to work

### ISSUE THREAD

**Issue by grendo** [auth0/Auth0.WinformsWPF#16] opened 2016-04-07 20:17 UTC
If you have 2 factor authentication switched on you login through say google, all that works but when the 2nd phase authentication pops up it seems to be broken.  There is no qr code on the page, seems to have a green bar at the bottom that might be the button.

**Comment by jerriep** [comment] 2016-04-25 02:13
Hey @grendo ,

I am unable to reproduce your problem. I have testing signing in with both a GitHub and a Google account, both of which have 2FA configured with Google Authenticator, and in both instances this works fine for me.

Any chance you can send me more details? Some screenshots, or a sample application which demonstrates the problem?

**Comment by jerriep** [comment] 2016-06-29 03:36
@grendo I have not received any feedback, so I am closing this issue for now.

Please let me know if you have a reproducible scenario to share, or can supply me with more info so I can reproduce it.

**Closed by jerriep** 2016-06-29 03:36 UTC
