### ISSUE TITLE
Login stop working?

### ISSUE THREAD

**Issue by h3ko** [auth0/Auth0.WinformsWPF#17] opened 2016-04-21 09:08 UTC
Hello,

It seems login stopped working. On simple login with widget:

`await auth0Client.LoginAsync(New WindowWrapper(Handle))`

we get UnauthorizedAccessException: 
Error UnauthorizedAccessException { Message: "State does not match", Data: [], InnerException: null, TargetSite: Void ThrowForNonSuccess(System.Threading.Tasks.Task), StackTrace..}

Auth0Client.cs, line 73:

Any ideas?

Kind regards, Martin

**Comment by jerriep** [comment] 2016-04-22 02:55
Hey @h3ko,

I am not able to reproduce by running our sample applications.

Can you please send me a sample which demonstrates the problem?

Thank you

**Comment by h3ko** [comment] 2016-04-22 06:51
Hey,

I've figured it out – the problem is with the »State« string which is passed as a query parameter and should be retured along with auth token.

1.)	Auth0Client – GetAuthenticator method:
var startUri = new Uri(authorizeUri + "&state=" + **this.State**);

2.)	Auth0User - accountProperties["state"] is null - state parameter is not included in fragments when request is returned

Google and Facebook providers return this state parameter but auth0 provider does not. It looks like some changes were introduced on the server side?

In my app I only create a client and call simple login, nothing else:
Dim auth0Client = New Auth0Client(Auth0Domain(), Auth0ClientId())
Dim user = await auth0Client.LoginAsync(New WindowWrapper(Handle))


For now I just removed this »state check« Auth0Client and it works…
/* 
   if (this.State != e.Account.State)
   {
tcs.TrySetException(new UnauthorizedAccessException("State does not match"));
   }
*/

**Comment by jerriep** [comment] 2016-04-25 02:09
I am unsure though why this is not working correctly for you, and it is
concerning me. I have tried with both a database connection as well as a
social connection (GitHub) and in both instances it works fine for me with
the code that checks for the state

Any chance you can isolate the problem in a sample project which you can
send to me?

**Comment by h3ko** [comment] 2016-05-08 15:18
Sorry for late response...

Simple example (WPF app, 4.6): https://www.dropbox.com/s/cjb0hmgrkc2f2cd/auth0example.zip?dl=0

Google provider works (returns the state string) and auth0 provider doesn't  (state is null in the response).

**Comment by jerriep** [comment] 2016-05-11 04:11
Hi @h3ko , this one has got me confused ;)

I have tested your sample locally and it works for me with both an Auth0 Database Connection as well as with Google. In both cases I sign in successfully, and in both cases if I inspect `auth0Client.CurrentUser` I can see the `State` property is set.

Is there anything non-standard about the app you registered in Auth0? Or perhaps your Database Connection is non-standard?

**Comment by h3ko** [comment] 2016-05-11 07:00
Yeah I bet it did :) I've tested it on a different Auth0 account and it works. Something has to be different/non-standard. I'll try to pinpoint the problem (maybe one of the rules, or something...) and get back to you. DB connection is sadly standard :)

**Comment by jerriep** [comment] 2016-05-11 07:31
Great thanks. If you can pinpoint the specifics let me know and I will see if I can fix it :)

**Comment by jerriep** [comment] 2016-05-20 03:39
@h3ko I am closing this issue for now. If you have more details in the future on how to reproduce, please reopen this issue or open a new issue.

**Closed by jerriep** 2016-05-20 03:39 UTC
